### ISSUE TITLE
Make the site responsive for smaller screen sizes

### ISSUE THREAD

**Issue by SoarinSkySagar** [SoarinSkySagar/FunSite#1]
As mentioned in the title, make the site responsive so that it can be viewed on smaller screen like mobile, tab, etc.

**Comment by Puskar-Roy** [comment]
Hey @SoarinSkySagar  I want to work on this issue, can u assign me?

**Comment by SoarinSkySagar** [comment]
Sure @Puskar-Roy, I'm assigning you this issue.

**Comment by Puskar-Roy** [comment]
Hey @SoarinSkySagar , I've sent a pull request, kindly check it.

**Comment by SoarinSkySagar** [comment]
Done
